#!/bin/bash

set -e

echo "========================================"
echo "Delete javascript files generated by tsc"
echo "========================================"

find src -name "*.js" -type f -delete
find src -name "*.js.map" -type f -delete

echo "JavaScript files removed successfully."